/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Aug 21, 2011, 9:53:41 AM
 */
package my.AFSA3;

/**
 *
 * @author Owner
 */
import java.io.*;
import java.io.IOException;
import javax.swing.*;
import java.util.Scanner;
import java.util.ArrayList;
import java.awt.*;

public class MainFrame extends javax.swing.JFrame {
    static ArrayList nameOfFiles = new ArrayList();
    static String out;
    static double Rmean1,Rmean2,Rmean3,Rstd1,Rstd2,Rstd3;
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AFS1txtBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AFS2txtBox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        AFS3txtBox = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        AFS4txtBox = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        AFS5txtBox = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        AFS6txtBox = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        AFS7txtBox = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        AFS8txtBox = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        AFS9txtBox = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        AFS10txtBox = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        AFSA_Output = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputPane = new javax.swing.JTextArea();
        AFSA_Analysis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ant Foraging Simulator Analyzer  NetLogo Version");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("AFS Files"));

        AFS1txtBox.setEditable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("AFS File 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AFS2txtBox.setEditable(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("AFS File 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AFS3txtBox.setEditable(false);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("AFS File 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        AFS4txtBox.setEditable(false);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("AFS File 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        AFS5txtBox.setEditable(false);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("AFS File 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        AFS6txtBox.setEditable(false);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("AFS File 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        AFS7txtBox.setEditable(false);
        AFS7txtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFS7txtBoxActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("AFS File 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        AFS8txtBox.setEditable(false);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("AFS File 8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        AFS9txtBox.setEditable(false);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("AFS File 9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        AFS10txtBox.setEditable(false);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("AFS File 10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AFS10txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS9txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS8txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS7txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS6txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS5txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS4txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS3txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS2txtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS1txtBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS1txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS2txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS3txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS4txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS5txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS6txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AFS7txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS8txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS9txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFS10txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("AFSA Output File"));

        AFSA_Output.setEditable(false);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Browse...");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AFSA_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFSA_Output, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Pane"));

        OutputPane.setColumns(20);
        OutputPane.setEditable(false);
        OutputPane.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        OutputPane.setRows(5);
        jScrollPane1.setViewportView(OutputPane);

        AFSA_Analysis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AFSA_Analysis.setText("Run AFS Analysis");
        AFSA_Analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFSA_AnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(AFSA_Analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AFSA_Analysis, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String holder;
        fc2 = new JFileChooser();
        int returnVal = fc2.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS2txtBox.setText(fc2.getSelectedFile().toString());
           holder = fc2.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AFS7txtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFS7txtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFS7txtBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String holder;
        fc1 = new JFileChooser();
        int returnVal = fc1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS1txtBox.setText(fc1.getSelectedFile().toString());
           holder = fc1.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String holder;
        fc3 = new JFileChooser();
        int returnVal = fc3.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS3txtBox.setText(fc3.getSelectedFile().toString());
           holder = fc3.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String holder;
        fc4 = new JFileChooser();
        int returnVal = fc4.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS4txtBox.setText(fc4.getSelectedFile().toString());
           holder = fc4.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String holder;
        fc5 = new JFileChooser();
        int returnVal = fc5.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS5txtBox.setText(fc5.getSelectedFile().toString());
           holder = fc5.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String holder;
        fc6 = new JFileChooser();
        int returnVal = fc6.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS6txtBox.setText(fc6.getSelectedFile().toString());
           holder = fc6.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       String holder;
        fc7 = new JFileChooser();
        int returnVal = fc7.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS7txtBox.setText(fc7.getSelectedFile().toString());
           holder = fc7.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String holder;
        fc8 = new JFileChooser();
        int returnVal = fc8.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS8txtBox.setText(fc8.getSelectedFile().toString());
           holder = fc8.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String holder;
        fc9 = new JFileChooser();
        int returnVal = fc9.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS9txtBox.setText(fc9.getSelectedFile().toString());
           holder = fc9.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       String holder;
        fc10 = new JFileChooser();
        int returnVal = fc10.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFS10txtBox.setText(fc10.getSelectedFile().toString());
           holder = fc10.getSelectedFile().toString();
           nameOfFiles.add(holder);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        vc = new JFileChooser();
        int returnVal = vc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            AFSA_Output.setText(vc.getSelectedFile().toString());
            out=vc.getSelectedFile().toString();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void AFSA_AnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFSA_AnalysisActionPerformed
        int length = nameOfFiles.size();
        int length1=150;
        
        Seed sid1 = new Seed();
        Seed sid2 = new Seed();
        Seed sid3 = new Seed();
        Seed sid4 = new Seed();

        double []PSR1=new double[length1];
        double []PSR2=new double[length1];
        double []PSR3=new double[length1];
        double []PSR4=new double[length1];

        double RSP1,RSP2,RSP3,RSP4;
        

        double []RR1=new double[length1];
        double []RR2=new double[length1];
        double []RR3=new double[length1];

        double []LogRR1 = new double[length1];
        double []LogRR2 = new double[length1];
        double []LogRR3 = new double[length1];

         

        int l1=0,l2=0,l3=0,l4=0;
        int e=0,y=0,b=0,v=0;
        int e1=0,e2=0,e3=0,e5=0;

        double RRMean1, RRMean2,RRMean3;
        double RRstd1,RRstd2,RRstd3;

        double LogRRMean1,LogRRMean2,LogRRMean3;
        double LogRRstd1,LogRRstd2,LogRRstd3;

        File Infile2 ;
        Scanner Input2;
        
        
        String filenames, filevalue;
        String out1= out;
        
        for(int i=0; i<length; i++) {
            filenames = nameOfFiles.get(i).toString();
            //OutputPane.append("Working with file " + filenames+"\n");
            Infile2 = new File(filenames);
            try{
                Input2 = new Scanner(Infile2);
                while (Input2.hasNext()) {
                    filevalue = Input2.next();
                    //System.out.println("value: " + filevalue);

                    if(filevalue.substring(0,1).equals("1")) {
                        sid1.InsertData(filevalue);
                       e1++;
                    } else
                        if(filevalue.substring(0,1).equals("2")) {
                            sid2.InsertData(filevalue);
                            e2++;
                        } else
                            if(filevalue.substring(0,1).equals("3")) {
                                sid3.InsertData(filevalue);
                               e3++;
                            } else
                                if(filevalue.substring(0,1).equals("5")) {
                                    sid4.InsertData(filevalue);
                                      e5++;
                                } else {
                        OutputPane.append("Corrupt data detected, please check AFS source file currently being processed\n.");
                        break;
                                }
                }//closing while loop bracket
              Input2.close();
            }//closing try bracket
            catch(FileNotFoundException ex) {
                OutputPane.append("File not found\n");

            }

            //System.out.println(sid4.Show());
            l1 = sid1.Length();
            l2 = sid2.Length();
            l3 = sid3.Length();
            l4 = sid4.Length();

            System.out.println("L1 is : "+l1);
            System.out.println("L2 is : "+l2);
            System.out.println("L3 is : "+l3);
            System.out.println("L4 is : "+l4);
            System.out.println("******* Run"+i);
             int [] red = new int[l1];
            int [] green = new int [l2];
            int [] purple = new int [l3];
            int [] blue = new int [l4];

            sid1.Reset();
            sid2.Reset();
            sid3.Reset();
            sid4.Reset();

           
            OutputPane.append("Red,Green,Purple and Blue seed arrays have been initialized\n");
            for (int m=0; m<l1; m++)
            {
                red[m] =Convert(sid1);
            }
            System.out.println("Red seed array initialized");
            int t1first=red[0];
            int t1=red.length;
            int t1last=red[(t1)-1];
            RSP1 = ((double)t1)/((double)t1last-(double)t1first);
            PSR1[e]=RSP1;
            RSP1=0.0;
            System.out.printf("Red PSR run %d calculated and the red array is %d",e,t1);
            e++;

            for (int j=0; j<l2; j++)
            {
                green[j] =Convert(sid2);
            }
            System.out.println("Green seed array initialized");
            int t2first=green[0];
            int t2=green.length;
            int t2last=green[(t2)-1];
            RSP2 = ((double)t2)/((double)t2last-(double)t2first);
            PSR2[y]=RSP2;
            System.out.printf("Green PSR run %d calculated and length of green array is %d",y,t2);
            y++;

            for (int q=0; q<l3; q++)
            {
                purple[q] =Convert(sid3);
            }
            System.out.println("Purple seed array initialized");
            int t3first=purple[0];
            int t3=purple.length;
            int t3last=purple[(t3)-1];
            RSP3 = ((double)t3)/((double)t3last-(double)t3first);
            PSR3[b]=RSP3;
            System.out.printf("Purple PSR run %d calculated and length of Purple array is %d",b,t3);
            b++;

            for (int l=0; l<l4; l++)
            {
                blue[l] =Convert(sid4);
            }
            System.out.println("Blue seed array initialized");
            int t4first=blue[0];
            int t4=blue.length;
            int t4last=blue[(t4)-1];
            RSP4 = ((double)t4)/((double)t4last-(double)t4first);
            PSR4[v]=RSP4;
            System.out.printf("Blue PSR run %d calculated and length of Blue array is %d",v,t4);
            v++;
         
            System.out.println("Emptying red seed holder");
            sid1.EmptySeedObject(t1);
            System.out.println("Emptying green seed holder");
            sid2.EmptySeedObject(t2);
            System.out.println("Emptying purple seed holder");
            sid3.EmptySeedObject(t3);
            System.out.println("Emptying blue seed holder");
            sid4.EmptySeedObject(t4);
            System.out.println("Seed objects emptied");
        }
        //Calculating Recruitment ratio values
          for(int u=0; u<length;u++)
          {
              RR1[u]=PSR1[u]/PSR4[u];
              RR2[u]=PSR2[u]/PSR4[u];
              RR3[u]=PSR3[u]/PSR4[u];
          }

        //Calculating logged recruitment ratio values
        for(int n=0;n<length;n++)
        {
        LogRR1[n]=Math.log(RR1[n])/Math.log(2.0);
        LogRR2[n]=Math.log(RR2[n])/Math.log(2.0);
        LogRR3[n]=Math.log(RR3[n])/Math.log(2.0);
        }
        OutputPane.append("All files have been processed\n");
        RRMean1= MeanFunc(RR1,length);
        RRMean2= MeanFunc(RR2,length);
        RRMean3= MeanFunc(RR3,length);

        RRstd1 = StandardDevFunc(RR1,length);
        RRstd2 = StandardDevFunc(RR2,length);
        RRstd3 = StandardDevFunc(RR3,length);

        LogRRMean1=MeanFunc(LogRR1,length);
        LogRRMean2=MeanFunc(LogRR2,length);
        LogRRMean3=MeanFunc(LogRR3,length);

        LogRRstd1= StandardDevFunc(LogRR1,length);
        LogRRstd2= StandardDevFunc(LogRR2,length);
        LogRRstd3= StandardDevFunc(LogRR3,length);

        Rmean1 = LogRRMean1;
        Rmean2 = LogRRMean2;
        Rmean3 = LogRRMean3;

        Rstd1=LogRRstd1;
        Rstd2=LogRRstd2;
        Rstd3=LogRRstd3;
        try{
            PrintWriter Outfile = new PrintWriter(out1);
            OutputPane.append("Writing data to outputfile " +out1+"\n");
            for(int h=0; h<length; h++)
                Outfile.printf("%11.10f    %11.10f    %11.10f    %11.10f    %11.10f    %11.10f    %11.10f    %11.10f    %11.10f    %11.10f \n",PSR1[h],PSR2[h],PSR3[h],PSR4[h],RR1[h],RR2[h],RR3[h],LogRR1[h],LogRR2[h],LogRR3[h]);
            Outfile.println("\n");
            Outfile.println("\n");
            Outfile.println("\n");
            
                Outfile.println("The Mean  and Standard Deviations of the Recruitment Ratios before Normalization:\n");
                Outfile.printf("The Mean and Standard Deviation for Recruitment Ratio 1(RR1): %11.10f & %11.10f respectively\n",RRMean1,RRstd1);
                Outfile.printf("The Mean and Standard Deviation for Recruitment Ratio 2(RR2): %11.10f & %11.10f respectively\n",RRMean2,RRstd2);
                Outfile.printf("The Mean and Standard Deviation for Recruitment Ratio 3(RR3): %11.10f & %11.10f respectively\n",RRMean3,RRstd3);
                Outfile.println("\n");
                Outfile.println("\n");
                Outfile.println("The Mean  and Standard Deviations of the Recruitment Ratios after Normalization:\n");
                Outfile.printf("Normalized Mean and Standard Deviation for Recruitment Ratio 1(RR1): %11.10f & %11.10f respectively\n",LogRRMean1,LogRRstd1);
                Outfile.printf("Normalized Mean and Standard Deviation for Recruitment Ratio 2(RR2): %11.10f & %11.10f respectively\n",LogRRMean2,LogRRstd2);
                Outfile.printf("Normalized Mean and Standard Deviation for Recruitment Ratio 3(RR3): %11.10f & %11.10f respectively\n",LogRRMean3,LogRRstd3);
            
            Outfile.close();
            OutputPane.append("All results have been written to output file.\n");
        } catch(FileNotFoundException ex) {
            OutputPane.append("Output file not found.\n");
        }
        
    }//GEN-LAST:event_AFSA_AnalysisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AFS10txtBox;
    private javax.swing.JTextField AFS1txtBox;
    private javax.swing.JTextField AFS2txtBox;
    private javax.swing.JTextField AFS3txtBox;
    private javax.swing.JTextField AFS4txtBox;
    private javax.swing.JTextField AFS5txtBox;
    private javax.swing.JTextField AFS6txtBox;
    private javax.swing.JTextField AFS7txtBox;
    private javax.swing.JTextField AFS8txtBox;
    private javax.swing.JTextField AFS9txtBox;
    private javax.swing.JButton AFSA_Analysis;
    private javax.swing.JTextField AFSA_Output;
    private javax.swing.JTextArea OutputPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private JFileChooser fc1;
private JFileChooser fc2;
private JFileChooser fc3;
private JFileChooser fc4;
private JFileChooser fc5;
private JFileChooser fc6;
private JFileChooser fc7;
private JFileChooser fc8;
private JFileChooser fc9;
private JFileChooser fc10;
private JFileChooser vc;


//Functions
public static double MeanFunc(double[] Arr, int q){
    double LocalMean;
	double Sum;
	Sum=0;

	for(int h=0; h<q; h++)
	{
       Sum= Sum + Arr[h];
	}

	LocalMean= Sum/q;


	return LocalMean;
}

public static double StandardDevFunc(double Arr[], int q){
	double StanDev;

	double Variance;

	double SumSquared;

	double LocalMean;

	double Sum;

	LocalMean=0;

	SumSquared=0;

	Sum=0;

	for(int h=0; h<q; h++)
	{
       Sum= Sum + Arr[h];
	}

	LocalMean= Sum/q;
	double LocalMeanSqr;
	LocalMeanSqr= Math.pow(LocalMean,2);

	for (int r=0; r<q; r++)
	{
      SumSquared=SumSquared +Math. pow(Arr[r],2);
	}

	Variance=(SumSquared-(q*LocalMeanSqr))/(q-1.0);

	StanDev=Math.sqrt(Variance);

	return StanDev;
}
public static int Convert(Seed obj)
    {
    int Hold=0;
    int size;
    String index1;
    String index2;
    index1 = obj.GetNext();
    size = index1.length();
    index2=index1.substring(2);
    Hold = Integer.parseInt(index2);
    return Hold;
    }
}
